{%- if values.componentName %}
  {%- set name = values.componentName %}
{%- else %}
  {%- set name = values.repoName %}
{% endif -%}

apiVersion: backstage.io/v1alpha1
{%- if values.entityKind %}
kind: ${{ values.entityKind }}
{%- else %}
kind: Component
{%- endif %}
metadata:
  name: ${{ name }}
  {%- if values.title %}
  title: ${{ values.title }}
  {%- endif %}
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  annotations:
    {%- if values.ci == "../../../skeletons/tekton/" %}
    tektonci/build-namespace: ${{ values.namespace }}
    janus-idp.io/tekton: ${{ name }}
    {%- endif %}

    {%- if values.ci == "../../../skeletons/azure/" %}
    dev.azure.com/build-definition: azure-${{ values.repoName }}-pipeline
    {%- endif %}
   
    argocd/app-selector: rht-gitops.com/janus-argocd=${{ values.repoName }}-bootstrap
    argocd/app-name: ${{ values.artifactId }}-dev
    backstage.io/kubernetes-id: ${{ name }}
    backstage.io/techdocs-ref: dir:.
    {%- if values.sourceControl == "gitlab.com" %}
    gitlab.com/project-slug: ${{ values.orgName }}/${{ values.repoName }}
    {%- elif values.sourceControl == "github.com" %}
    github.com/project-slug: ${{ values.orgName }}/${{ values.repoName }}
    {%- elif values.sourceControl == "dev.azure.com" %}
    dev.azure.com/project-repo: "Developer Hub Demo/${{ values.repoName }}"
    {%- endif %}
    {%- if values.imageRegistry == "Quay" %}
    quay.io/repository-slug: ${{ values.imageOrganization }}/${{ values.imageName }}
    {%- endif %}
  links:
    - url: https://devspaces.apps.cluster-h6fh7.sandbox550.opentlc.com/#https://anattama@dev.azure.com/anattama/Developer%20Hub%20Demo/_git/${{ values.repoName }}
      title: OpenShift Dev Spaces (VS Code editor)
      icon: web
    - url: https://${{ values.repoName }}-gateway-${{ values.repoName }}-dev.apps.cluster-h6fh7.sandbox550.opentlc.com/api/hello
      title: Deployed Application
      icon: web  
  tags:
    - java
    - spring-boot
    - openshift-service-mesh
    - azure-pipelines-ci
    - argocd-gitops
    - azure-repos
spec:
  type: ${{ values.applicationType }}
  {%- if values.system %}
  system: ${{ values.system }}
  {%- endif %}
  {%- if values.lifecycle %}
  lifecycle: ${{ values.lifecycle }}
  {%- else %}
  lifecycle: production
  {%- endif %}
  owner: ${{ values.owner }}
  {%- if values.dependsOn %}
  dependsOn:
    - ${{ values.dependsOn }}
  {%- endif %}
  {%- if values.partOf %}
  partOf:
    - ${{ values.partOf }}
  {%- endif %}
