kind: DestinationRule
apiVersion: networking.istio.io/v1beta1
metadata:
  name: ${{ values.component_id }}-dr
  namespace: "{{ .Values.namespace.name }}"
spec:
  host: ${{ values.component_id }}
  subsets:
    - name: v1
      labels:
        version: v1
