apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ${{ values.component_id }}-dev-ingress
  namespace: ${{ values.component_id }}-dev
spec:
  podSelector:
    matchLabels:
      istio: ${{ values.component_id }}-dev-gateway
  ingress:
    - {}
  policyTypes:
  - Ingress  