apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${{ values.component_id }}-dev-gateway-sds-role
  namespace: ${{ values.component_id }}-dev
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]