apiVersion: v1
kind: Service
metadata:
  name: ${{ values.component_id }}-dev-gateway
  namespace: ${{ values.component_id }}-dev
spec:
  type: ClusterIP
  selector:
    istio: ${{ values.component_id }}-dev-gateway
  ports:
  - name: http2
    port: 80
    targetPort: 8080