apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.component_id }}-dev-gateway
  namespace: ${{ values.component_id }}-dev
spec:
  selector:
    matchLabels:
      istio: ${{ values.component_id }}-dev-gateway
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
      labels:
        istio: ${{ values.component_id }}-dev-gateway
        sidecar.istio.io/inject: "true" 
    spec:
      containers:
      - name: istio-proxy
        image: auto