apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${{ values.component_id }}-dev-gateway-sds-rolebinding
  namespace: ${{ values.component_id }}-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${{ values.component_id }}-dev-gateway-sds-role
subjects:
- kind: ServiceAccount
  name: default