apiVersion: maistra.io/v1
kind: ServiceMeshMember
metadata:
  name: default
  namespace:  {{ .Values.namespace.name }}
spec:
  controlPlaneRef:
    name: basic-control-plane
    namespace: istio-system